### ISSUE TITLE
getMeetings missing meetings xml node if no meetings running

### ISSUE THREAD

**Issue by SamuelWei** [blindsidenetworks/scalelite#479]
I noticed that the PHP Api fails if scalelite has no meetings running. 

I compared the response of scalelite and bbb and noticed two differences:

- The response message if different (Uppercase and a dot at the end)
- The node meetings is missing

**Scalelite**
```xml
<response>
  <returncode>SUCCESS</returncode>
  <messageKey>noMeetings</messageKey>
  <message>No meetings were found on this server.</message>
</response>
```

**BBB**
```xml
<response>
  <returncode>SUCCESS</returncode>
  <meetings/>
  <messageKey>noMeetings</messageKey>
  <message>no meetings were found on this server</message>
</response>
```

**Comment by SamuelWei** [comment]
Hi @jfederico I use Scalelite v1.0.7, BBB v2.2.32 and our BBB API Fork (https://github.com/littleredbutton/bigbluebutton-api-php) v3.3.0

I think the versions are not as important as you can easily see the differences in the source code: [Scalelite](https://github.com/blindsidenetworks/scalelite/blob/07f0f0ebab626b7d829d67e5cbd8544bc216ec83/app/controllers/bigbluebutton_api_controller.rb#L387) vs [BBB](https://github.com/bigbluebutton/bigbluebutton/blob/d30f0dc710b4216c5b26769dbb9b41813cf5d4c0/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L907)

See the mentioned issue to learn how we created a work-around for our bbb api client

**Comment by jfederico** [comment]
@SamuelWei yeah, the question was more to see if that was something that we introduced in one of the last releases or if it was coming from before. You just confirmed to me that this was indeed a long standing issue.

It is fixed and merged, if you pull images from master you should have it fixed now.

cheers

**Comment by SamuelWei** [comment]
@jfederico To me it looks like the empty meetings xml node is still missing, that's what caused problems with the api and is a different behavior compared to bbb.
